### ISSUE TITLE
FormatCheckRequested address book level 2

### ISSUE THREAD

**Issue by PhilipPhil** [nus-cs2103-AY1819S2/forum#23]
I have a FormatCheckRequested address book level 2. I fixed it but it didn't go away.

**Comment by ccristina** [comment]
Hi,

Unfortunately [nus-se-pr-bot](/nus-se-pr-bot) was not updated with the latest naming conventions on time. We will rectify the problem for the next weeks. 

Continue to use the format `[WEEK_ID][TEAM_ID]Your Name` for individual PRs and ignore the comment from the bot. 

Best regards,
Cristina.
