### ISSUE TITLE
Can we rename all variables, filenames, classnames etc in one commit?

### ISSUE THREAD

**Issue by rbth7e5** [nus-cs2103-AY1819S2/forum#36]
Will it violate the incremental updates constraint? Current I am trying to morph my project by changing Person to another name. This requires updating 2121 lines of code, which I can do in one go using Intellij's refactoring feature. I don't see how I can break this update down any further since the Person name is so inextricably interlinked throughout the project.

**Comment by okkhoy** [comment]
Suggested: make one commit for each refactoring action (eg., variable rename - one commit; method rename -- one commit). Easier to recover in case of a mess as against putting **all** refactoring in one commit.

Tip: Ensure that in each such commit there are no other changes.
