### ISSUE TITLE
Definition of 'Repository' in the textbook

### ISSUE THREAD

**Issue by mechome** [nus-cs2103-AY1819S2/forum#4]
Hello,

In the online textbook W2.2b, it says that "the repository is the database where the meta-data about the revision history are stored", which to me seems like it refers only to the meta-data folder. Instead, from what I know, it refers to the entire directory of the project + the meta-data about the history and revisions.

It seems a bit misleading to me.

**Comment by ccristina** [comment]
Hi,

You are right: the repository stores the files that are changed and the meta-data about the revision history. We will clarify in the textbook. 

Thanks for pointing out. 
Cristina.
