### ISSUE TITLE
Navigability

### ISSUE THREAD

**Issue by Jackimaru96** [nus-cs2103-AY1819S2/forum#41]
## Question about Navigability

Dear Profs/All

This is the question I asked in the Lecture in week 6.
**How is navigability shown in class/object diagrams?**

As seen from the first photo taken from the lecture slides, it was mentioned that the navigability is different as indicated by the *label's* direction. However, according to the CS2103T website topics lecture notes, the label's direction has nothing to do with **navigability** and just describes the *meaning of the association and the direction it is read.*

Instead, the navigability should be shown by the **direction of the arrowhead** as shown in the 2nd photo. If so, then for the lecture note's example, the navigability should be the same (that is, only Student is aware of Book and Book is not aware of Student)

Can someone confirm this? :) Thank you!

### Lecture note:
![image](https://user-images.githubusercontent.com/29891801/53538892-68993300-3b4a-11e9-88e8-4b613d85496e.png)

### Website description of labels direction:
![image](https://user-images.githubusercontent.com/29891801/53539058-00971c80-3b4b-11e9-9bfd-c9fba115147c.png)

### Website description how navigability is shown:
![image](https://user-images.githubusercontent.com/29891801/53539062-0856c100-3b4b-11e9-8283-06089fd4982e.png)

**Comment by ccristina** [comment]
Hello,

Thank you for clarifying this question here. 

After watching the webcast, I could fully understand your question. I used the term "navigability" to incorrectly describe the arrow next to the label. Please disregard the wrong usage of this term. However, the explanation given in class on the meaning of these diagrams is correct.   

As mentioned in class as well, the arrow head next to the label `borrows` or `borrowed by` shows how to READ the association using the label. The association arrow (main line connecting the boxes ending with an arrow) shows that the Student knows about the Book (Student has a reference to Book) - and this is "navigability". As such, the textbook section saying that the association arrow shows the navigability is correct. 

Let me know if you still have questions. 

Best regards,
Cristina.

**Comment by Jackimaru96** [comment]
Hello Professor Carbunaru, 

Thank you for your clarification! I am clear of this issue now :)

Regards
Jack Chen
