### ISSUE TITLE
Unable to pass all test case from AB4

### ISSUE THREAD

**Issue by NgWeiXin** [nus-cs2103-AY1819S2/forum#42]
Setting up process was:
1. Clone the latest AB4 (as of 04/03/19) to local
2. import project with 'build.gradle'
3. SDK set to be Java 9.0.4
4. Run './gradlew processResources' successfully
5. Run 'All Test'
6. Failed 15 test cases (did not move cursor while test is running)

<img width="1392" alt="screenshot 2019-03-04 at 5 30 52 pm" src="https://user-images.githubusercontent.com/41330555/53726028-1ccaee80-3ea8-11e9-9022-a707bddd9b11.png">

**Comment by sreycodes** [comment]
As this issue is still not resolved, is it fine to make PRs (for today's deadline) which do not pass Travis?
@okkhoy @bqnguyen94

**Comment by okkhoy** [comment]
Sorry guys! I didn't get time to check this. For now you can disable those tests and PR.
Will take a look at the earliest today.

**Comment by okkhoy** [comment]
@NgWeiXin see: https://github.com/se-edu/addressbook-level4/issues/979 if it is relevant

**Comment by NgWeiXin** [comment]
@okkhoy Hello Prof! Thank you for the reference link! It is working now!
