### ISSUE TITLE
Developer Photo not shown on Project List

### ISSUE THREAD

**Issue by r4venz** [nus-cs2103-AY1819S2/forum#48]
I have changed the image file name to github username.png, but the photo is still not shown on the project list. Anyone knows what happened?

**Comment by okkhoy** [comment]
@Miaaaaa97 among the missing photos, I don't find any link that relates to your username. Can you please post the link to your organization?

**Comment by r4venz** [comment]
> @Miaaaaa97 among the missing photos, I don't find any link that relates to your username. Can you please post the link to your organization?

The photos suddenly showed up. Thank you for your reply :)
