### ISSUE TITLE
Update diagrams in Developer Guide

### ISSUE THREAD

**Issue by halcyoneee** [nus-cs2103-AY1819S2/forum#49]
How should we coordinate in updating diagrams in our DG? Some diagrams are generic enough that multiple people may be working on it simultaneously. However as we were told to not have more than 1 PR/week, it will be rather time-consuming to deal with ppt merge conflict.

So should we just let 1 person do the final update on all the generics ppt and diagrams? Outside of GitHub, we will collaborate on the update, just that on paper, it seems like only one person is making the update. Is this okay? Or is there a better way to do this?

**Comment by thomastanck** [comment]
I'm thinking of using PlantUML to generate diagrams for our team. Currently we haven't started using the tool, however. You can check out my PR to see how I set up the tool: cs2103-ay1819s2-w10-1/main#18 The tool lets you generate UML diagrams in the docs/diagrams folder to their own .png files in the compiled output which you can then link to within your .adoc files (I think).

You'll definitely need to read PlantUML docs: http://plantuml.com/sitemap-language-specification

**Comment by halcyoneee** [comment]
> I'm thinking of using PlantUML to generate diagrams for our team. Currently we haven't started using the tool, however. You can check out my PR to see how I set up the tool: [CS2103-AY1819S2-W10-1/main#18](https://github.com/CS2103-AY1819S2-W10-1/main/pull/18) The tool lets you generate UML diagrams in the docs/diagrams folder to their own .png files in the compiled output which you can then link to within your .adoc files (I think).
> 
> You'll definitely need to read PlantUML docs: http://plantuml.com/sitemap-language-specification

Looks interesting, thanks for the suggestion will take a look into it.

**Comment by ccristina** [comment]
Hi,

One PR per week per team member is not a strict limit. 

We are aware that for some diagrams more than one person will be involved. We will evaluate your portfolio at the end of the semester. Your portfolio should contain individual extracts from UG and DG. As such, you should also focus on having explanations about your own implementation from DG. For the team's (general) diagrams you might decide to split them among team members based on relevance when you include them in the portfolio. 

We do not check your edits on .ppt directly, from one week to another. Different teams will use different tools, and it might be that a general diagram is added by one team member.


Best regards,
Cristina.

**Comment by halcyoneee** [comment]
> Hi,
> 
> One PR per week per team member is not a strict limit.
> 
> We are aware that for some diagrams more than one person will be involved. We will evaluate your portfolio at the end of the semester. Your portfolio should contain individual extracts from UG and DG. As such, you should also focus on having explanations about your own implementation from DG. For the team's (general) diagrams you might decide to split them among team members based on relevance when you include them in the portfolio.
> 
> We do not check your edits on .ppt directly, from one week to another. Different teams will use different tools, and it might be that a general diagram is added by one team member.
> 
> Best regards,
> Cristina.

Okay got it, thanks.
