### ISSUE TITLE
Does the bot track PR to other (non-master) branches?

### ISSUE THREAD

**Issue by lingyanhao** [nus-cs2103-AY1819S2/forum#53]
In particular, we are planning to do all our main development to a branch separate from the master branch.

Will all our progress be correctly tracked?

**Comment by okkhoy** [comment]
@lingyanhao No. Only PR and merges to the master branch are checked.

**Comment by halcyoneee** [comment]
@okkhoy Just to clarify, so for mid milestone do we need to PR and merge to master branch in order for the feedback bot to check our progress?

**Comment by okkhoy** [comment]
Yes. All checks will be done on the master branch only.
