### ISSUE TITLE
`gradlew checkStyleMain` :compileJava error

### ISSUE THREAD

**Issue by Jackimaru96** [nus-cs2103-AY1819S2/forum#54]
I tried to run `gradlew checkStyleMain` on terminal in Intellij, this was the error message that came out:
![image](https://user-images.githubusercontent.com/29891801/54213694-c9981200-451f-11e9-9860-f4c4ff14b1c6.png)

I've tried [this solution](https://dev.to/hcnenseth/comment/3e3l), setting JAVA_HOME in Path variables but that didn't work as well.

Any ideas?

## EDIT: Somehow it works now; btw I'm using Windows

Here are the things that I did (not sure what actually triggered it to become successful)
- Added JAVA_HOME variable to point to jdk directory (without bin)
- Added %JAVA_HOME%\bin into Path variable in System variable
- In intelij, used `Invalidate caches / Restart` under File

**Comment by okkhoy** [comment]
@Jackimaru96 I am _guessing_ your JAVA_HOME made the difference?

Will close the issue.

**Comment by pyokagan** [comment]
Sometimes you need to restart the computer or log in and log out in order for environment variable changes to take effect on Windows.
