### ISSUE TITLE
Bot does not detect picture

### ISSUE THREAD

**Issue by wfxronald** [nus-cs2103-AY1819S2/forum#55]
By commit: a714f5c98f5342aa7c69ba8013a48e4a44025048, the group has updated pictures in .png format and the aboutUs page has reflected this change, but the bot does not detect this change: https://github.com/CS2103-AY1819S2-W13-4/main/issues/58

**Comment by okkhoy** [comment]
Moved the conversation to your team's issue tracker. Closing this issue
