### ISSUE TITLE
Setting up RepoSense

### ISSUE THREAD

**Issue by Jackimaru96** [nus-cs2103-AY1819S2/forum#59]
May I inquire how to set up RepoSense? 

Is it [this?](https://github.com/reposense/RepoSense/blob/release/docs/UserGuide.md#getting-started)

If the instructions in the above link is correct, does this mean we have to execute the command every time we commit so that it'll update the local report in `reposense-report`? 
Or is there another way of setting up RepoSense?
If that's the case we do not have to use `@@author` tags right?

**Comment by okkhoy** [comment]
@Jackimaru96 the link you posted is correct.

> If the instructions in the above link is correct, does this mean we have to execute the command every time we commit so that it'll update the local report in reposense-report?

No, that would be an overkill. You can do it, maybe, once a week to see how things are.

> Or is there another way of setting up RepoSense?

We are in the process of setting up RepoSense for the entire class (link will be made available on the module website). This picks up your contributions from GitHub to do the analysis. 
This is pretty much what we use later for grading your code. So you may simply rely on the weekly report that we publish.

**Comment by Jackimaru96** [comment]
@okkhoy Thank you Prof for your reply.

> We are in the process of setting up RepoSense for the entire class (link will be made available on the module website). This picks up your contributions from GitHub to do the analysis.
This is pretty much what we use later for grading your code. So you may simply rely on the weekly report that we publish.

Does that mean we do not have to do anything for RepoSense as of now? 
Or do we need to generate the RepoSense report and place it in our team remote repo so that it can be picked up?

**Comment by okkhoy** [comment]
You don't have to do anything as of now. 😃 

We can take a look at outliers (if any) later once our RepoSense report is up.
