### ISSUE TITLE
'javac' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by PhilipPhil** [nus-cs2103-AY1819S2/forum#6]
I've been trying to figure out how to fix this problem when I try to run the test. I don't know what to do. I've been trying to read stack exchange and find videos but nothing is helping.

**Comment by fterh** [comment]
Add your java installation directory to your system PATH

**Comment by JonathanLeeWH** [comment]
@PhilipPhil To add on to what @fterh said if you are using Windows, if it still does not work after adding it to your system PATH, restart your computer.

**Comment by PhilipPhil** [comment]
how do I add it to my system path?

**Comment by Justin-Ong** [comment]
https://www.java.com/en/download/help/path.xml

If you're using Windows, the variable should be C:\Program Files\Java\jdk-9.0.4\bin or something similar.

**Comment by okkhoy** [comment]
@PhilipPhil Did you try searching for the error message on the Internet? 
What steps did you try? 
What is the outcome?

**Comment by PhilipPhil** [comment]
@okkhoy 

I did exactly this.

Windows 10 and Windows 8
In Search, search for and then select: System (Control Panel)
Click the Advanced system settings link.
Click Environment Variables. In the section System Variables, find the PATH environment variable and select it. Click Edit. If the PATH environment variable does not exist, click New.
In the Edit System Variable (or New System Variable) window, specify the value of the PATH environment variable. Click OK. Close all remaining windows by clicking OK.
Reopen Command prompt window, and run your java code.

 I also tried restarting my computer. I set it to the folder you told me to set to in class. It's still not working.

I've also tried uninstalling Java9 and reinstalling java 9.

I then spent all of last night googling thing and reading different stack exchange pages I still can't get it to run.

**Comment by PhilipPhil** [comment]
![omg](https://user-images.githubusercontent.com/44811794/51784119-38432b00-217f-11e9-9b01-6232f386d427.JPG)
I've set the paths. I restarted my computer. I don't know why it doesn't work.

**Comment by JonathanLeeWH** [comment]
> https://www.java.com/en/download/help/path.xml
> 
> If you're using Windows, the variable should be C:\Program Files\Java\jdk-9.0.4\bin or something similar.

Please refer to the above quote provided by @Justin-Ong. The reason after changing the environment variables and restarting the computer it still does not work is from what I can see based on the screenshot you are placing the directory of your project directory in the PATH directory.

Please edit both PATH to `C:\Program Files\Java\jdk-9.0.4\bin` assuming you install the Java jdk as provided by the tutor on LumiNUS and also assuming this is your java installation directory.

I think it would be good if you provide us with an update on the outcome and which method works and whether the solutions provided by others are helpful to you so at least we know whether your issue has been resolved and it may be helpful for others in the future. Screenshots are also useful.

**Comment by okkhoy** [comment]
@PhilipPhil @JonathanLeeWH is correct. Edit both paths, remove addressbook-level1 from the path.

**Comment by PhilipPhil** [comment]
it worked!!! Thank you for all the help guys!

**Comment by linehammer** [comment]
Windows OS searches the current directory and the directories listed in the PATH environment variable for executable programs. JDK's programs (such as Java compiler javac.exe and Java runtime java.exe) reside in directory "\bin" (where denotes the JDK installed directory, e.g., C:\Program Files\Java\jdk1.8.0_xx). You need to include the "\bin" directory in the [Java Path](http://net-informations.com/java/basics/path.htm).

- First make sure you have installed jdk and jre, both are installed with the java software development kit. The installation folder is typically C:\Program Files\Java.

- Now go to Computer > Properties > Advanced system settings in the advanced tab click on Environment Variables

- In System variables find the variable named Path, in the value of Path you will find a java path like C:\ProgramData\Oracle\Java\javapath, just change it to C:\Program Files\Java\jdk1.x.x_x\bin.
