### ISSUE TITLE
RepoSense is unable to recognise my account

### ISSUE THREAD

**Issue by iwle** [nus-cs2103-AY1819S2/forum#62]
Our team has configured RepoSense with the `_reposense/config.json`. However, it is still unable to detect my (@iwle) commits even if we run it locally. Are there any steps that we can take to debug this issue? Thanks!

**Comment by rbth7e5** [comment]
check your git bash username and if it matches

**Comment by iwle** [comment]
Thanks @rbth7e5! Works now.
