### ISSUE TITLE
Unable to open .fxml files in SceneBuilder

### ISSUE THREAD

**Issue by geezlouisee** [nus-cs2103-AY1819S2/forum#65]
Hi,

My teammates and I are experiencing this problem where we are unable to open `MainWindow.fxml` and `HelpWindow.fxml` in SceneBuilder. We get a message that says the "Content of this Document cannot be displayed" instead.

![image](https://user-images.githubusercontent.com/39251616/54903306-8c1b8780-4f16-11e9-8c88-a613c6e8e2b4.png)

Does anyone know how we can go about solving this? Thanks in advance!

**Comment by fterh** [comment]
Did the contents of your file get corrupted? Maybe a missing character or an extra character somewhere?

You can try checking out an earlier version of the file that works, then reviewing the commits from then till now, and validating every line change to isolate the problem.

**Comment by pyokagan** [comment]
Make sure you are using Gluon SceneBuilder for Java 11. It's a relatively recent feature and I don't think Gluon updates the Java 8 version any more.

**Comment by geezlouisee** [comment]
We managed to resolved the problem by downloading a developmental snapshot of Gluon SceneBuilder. Thanks for the help!
