### ISSUE TITLE
What does Neumann-complete test suite mean?

### ISSUE THREAD

**Issue by amuletxheart** [nus-cs2103-AY1819S2/forum#79]
I cannot find this phrase referenced anywhere in the textbook or online in any literature. Can someone explain what this term means?

Any help is much appreciated.

**Comment by ccristina** [comment]
Hi,

This is a nonsense question, put there to let you practice how to respond to an incorrect question. 

No such deliberately incorrect questions in the actual exam paper though!

Best regards,
Cristina.
