### ISSUE TITLE
Bugs related to failure to rename

### ISSUE THREAD

**Issue by lingyanhao** [nus-cs2103-AY1819S2/forum#87]
There are some bugs reported related to not renaming the files to our application.

In particular, leaving the file name as `addressbook.json` was reported as a bug.
May I know the teaching team's stand on this issue?

Are we allowed to reject such bugs? If not, how do we decide who should take responsibility for it? Or are we supposed to accept the bug as a team?

Please advice.

**Comment by okkhoy** [comment]
This is just attention to some details, but not necessarily a bug.
You can reject it.
