### ISSUE TITLE
Java release version 11 not supported

### ISSUE THREAD

**Issue by roanurquhart** [nus-cs2103-AY1819S2/forum#9]
I have Java 9, but when I try to run AddressBook-Level1 I get an error regarding Java release version 11 not supported.
<img width="676" alt="screen shot 2019-01-28 at 12 52 32 pm" src="https://user-images.githubusercontent.com/27874046/51815399-9dbc2680-22fb-11e9-9819-ab536da9eeb4.png">
Im not sure what the issue is or how to resolve it.

**Comment by JonathanLeeWH** [comment]
@roanurquhart As the error suggested you install Java 9 JDK and you most likely have more than version of Java JDK in your installation directory. You can search the error online but what it actually means it that compilation of your addressbook1 source code is with Java 9 JDK but you are trying to do so with Java 11. There are some licensing changes in Java 11 you can check Oracle website for more details but to answer your question can you try the solution below and reply whether it works:

Go to intelliJ > File > Project Structure > JDK > Make sure Java 9.0.4 JDK is selected and also the language level is set to 9.

**Comment by roanurquhart** [comment]
@JonathanLeeWH Thank you so much that worked!
