### ISSUE TITLE
Should we tag duplicate issues with 'response.', 'severity.', etc.

### ISSUE THREAD

**Issue by DigiPie** [nus-cs2103-AY1819S2/forum#90]
If there is an issue which is a duplicate of another issue (to me), should we still tag it with 'response.', 'severity.' and 'type.' given that the 'Duplicate of ...' requirement has already been done?

For example:
![image](https://user-images.githubusercontent.com/13582874/56468740-121de600-6463-11e9-966b-4db34f240deb.png)

Given:

> We recommend choosing type.*, severity.* and assignee even for bugs you are not accepting. Reason: your non-acceptance may be rejected by the tutor later, in which case we need to grade it as an accepted bug.

Should we do the same for bugs we label as duplicates?

**Comment by kylase-learning** [comment]
I don't think you need to.

**Comment by ccristina** [comment]
Hi,

In case the bug is not a duplicate after the TAs investigate, it would be better to have a severity, type, and assignee. Otherwise we will consider as same with bug you say “duplicate of”.

Best regards,
Cristina.

**Comment by DigiPie** [comment]
Thanks for your responses! 👍
