### ISSUE TITLE
Reposense contributions lost after this week's update

### ISSUE THREAD

**Issue by daviddl9** [nus-cs2103-AY1819S2/forum#92]
Dear profs,

When viewing the RepoSense report in the module website, it seems that the refresh that took place for today cleared all my previous contributions that took place before the 8th of April. Am not too sure what exactly happened, because I did not change my username / details in the github reposense config file (It was showing my contributions accurately before today). Tried to look this issue up the Reposense UG but could not seem to identify the cause of this problem. 

Please help!

**Comment by okkhoy** [comment]
![image](https://user-images.githubusercontent.com/1023494/56489495-76e54900-6514-11e9-9d8a-8c2d9af0430d.png)
is this not the correct one, @daviddl9 ?

**Comment by daviddl9** [comment]
Nope, this only shows the records from 8th of April onwards. 
All my contributions from February (which were showing fine last week) are no longer being shown

**Comment by okkhoy** [comment]
Check with your team, your repository was updated yesterday. 
Please run reposense locally to identify and fix all errors before pushing to your repo.

**Comment by daviddl9** [comment]
Okay, it has been rectified. It should be reflected accurately with the next update. Thanks!
